"""Write the generated MyST sources and run the strict Sphinx build."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sphinx.cmd.build import build_main

if TYPE_CHECKING:
    from pathlib import Path

# The conf.py written next to the generated pages. Kept minimal: MyST parsing
# with colon-fence admonitions, the furo theme, and the rst2pdf builder for
# the optional PDF rendering.
_CONF = """# Generated by vreport — regenerated on every run, do not edit.
import os

project = {project!r}
author = "vreport"
extensions = ["myst_parser", "rst2pdf.pdfbuilder"]
myst_enable_extensions = ["colon_fence"]
exclude_patterns = ["_build"]
html_theme = "furo"
html_title = {project!r}
pdf_documents = [("index", "verification-report", {project!r}, "vreport")]
pdf_use_index = False
pdf_style_path = [os.path.dirname(__file__)]
pdf_stylesheets = ["sphinx", "vreport"]
"""

# rst2pdf stylesheet: a smaller monospace face so the verbatim gnatprove.out
# summary table (100+ columns) fits the PDF frame without shrink-to-fit, and
# aliases for the Sphinx cross-reference classes rst2pdf has no styles for.
_PDF_STYLE = """styles:
  code:
    fontSize: 6.5
  std:
    parent: normal
  std-ref:
    parent: normal
"""


def write_sphinx_sources(pages: dict[str, str], srcdir: Path, title: str) -> None:
    """Write conf.py, the PDF stylesheet, and the generated pages into `srcdir`."""
    srcdir.mkdir(parents=True, exist_ok=True)
    (srcdir / "conf.py").write_text(_CONF.format(project=title))
    (srcdir / "vreport.yaml").write_text(_PDF_STYLE)
    for name, content in pages.items():
        (srcdir / name).write_text(content)


def build_html(srcdir: Path, outdir: Path) -> int:
    """
    Build HTML with warnings-as-errors and nitpicky reference checking.

    The strict flags are the report's oracle: a dangling claim-to-evidence
    reference fails the build instead of shipping a broken report.
    """
    return build_main(["-b", "html", "-W", "-n", "-E", "-q", str(srcdir), str(outdir)])


def build_pdf(srcdir: Path, outdir: Path) -> int:
    """
    Build the PDF rendering (rst2pdf: pure Python, no TeX toolchain needed).

    Deliberately not run with `-W`: the strict HTML build is the report's
    correctness oracle, and the PDF is a convenience rendering of the same
    sources whose builder may warn on cosmetic layout issues.
    """
    return build_main(["-b", "pdf", "-E", "-q", str(srcdir), str(outdir)])
