"""Write the generated MyST sources and run the strict Sphinx build."""

from __future__ import annotations

from typing import TYPE_CHECKING

from sphinx.cmd.build import build_main

if TYPE_CHECKING:
    from pathlib import Path

# The conf.py written next to the generated pages. Kept minimal: MyST parsing
# with colon-fence admonitions, and the furo theme.
_CONF = """# Generated by vreport — regenerated on every run, do not edit.
project = {project!r}
author = "vreport"
extensions = ["myst_parser"]
myst_enable_extensions = ["colon_fence"]
exclude_patterns = ["_build"]
html_theme = "furo"
html_title = {project!r}
"""


def write_sphinx_sources(pages: dict[str, str], srcdir: Path, title: str) -> None:
    """Write conf.py and the generated pages into `srcdir`."""
    srcdir.mkdir(parents=True, exist_ok=True)
    (srcdir / "conf.py").write_text(_CONF.format(project=title))
    for name, content in pages.items():
        (srcdir / name).write_text(content)


def build_html(srcdir: Path, outdir: Path) -> int:
    """
    Build HTML with warnings-as-errors and nitpicky reference checking.

    The strict flags are the report's oracle: a dangling claim-to-evidence
    reference fails the build instead of shipping a broken report.
    """
    return build_main(["-b", "html", "-W", "-n", "-E", "-q", str(srcdir), str(outdir)])
