variables:
  BASE_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_DEPENDENCY_PROXY_SERVER}
  ANOD: $BASE_URL/eng/shared/anod
  INTERNAL_ALIRE_SCRIPTS: $BASE_URL/eng/devops/internal-alire-scripts.git
  INTERNAL_ALIRE_INDEX: $BASE_URL/eng/devops/internal-alire-index
  UV_PYTHON_DOWNLOADS: never

stages:
  - validate
  - build
  - check

include:
  - component: $CI_SERVER_FQDN/eng/gitlab-templates/check-issue@~latest

default:
  interruptible: true

.default_rules:
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.x86_64-linux-pro:
  variables:
    OS: Linux
    PLATFORM: x86_64-linux
  services:
    - image:e3
    - cpu:4

.x86_64-linux-community:
  variables:
    OS: Linux
    PLATFORM: x86_64-linux
  services:
    - image:e3
    - cpu:4
    # Allow connecting to the internet
    - security_group:GitLabRunnerTasksExecPrivilegedSG

# Test the `reqs` requirements validation tool, then validate the requirements
# with it.
validate-requirements:
  stage: validate
  extends:
    - .default_rules
  services:
    - image:e3-py313
    - cpu:2
  script:
    - pip install uv
    - unset VIRTUAL_ENV
    - make test-reqs-engine
    - make validate-reqs

.pro:
  stage: build
  extends:
     - .x86_64-linux-pro
     - .default_rules
  before_script:
    # Deploy a sandbox
    - anod init wave
    - export ANOD_DEFAULT_SANDBOX_DIR=$(pwd)/wave

    # Install alire
    - anod install alire
    - eval $(anod printenv alire)

    # Setup alire to use our local index
    - alr -n index --name=adacore --add=git+$INTERNAL_ALIRE_INDEX

    # Setup alire to use our downloader helper
    - git clone --depth=1 $INTERNAL_ALIRE_SCRIPTS /tmp/internal-alire-scripts
    - alr -n settings --global --set --builtin origins.archive.download_cmd \
        "/tmp/internal-alire-scripts/adacore_registries_download.py"

    # Sanity check
    - alr --version

# Native build and test with coverage.
pro:x86_64-linux:
  extends: .pro
  script:
    # Install stable specs
    - for spec in gnat gnatformat spark2014 gnatcov gnattest ; do
        anod install $spec --qualifier=stable ;
        eval $(anod printenv $spec --qualifier=stable) ;
      done

    # Sanity check
    - gnat --version
    - gnatprove --version

    # Build
    - make build-native

    # Test with coverage
    - make coverage-instrumentation
    - make coverage-build
    - make coverage-test-pro
    - make coverage-report-html
    - make coverage-report-cobertura
    - make coverage-report-text

    # Publish the HTML coverage report
    - gnatcov_report_dir=$(pwd)/reports/coverage/
    - |
      if [[ $CI_PIPELINE_SOURCE = "merge_request_event" ]]; then
        target_subdir=MRs/$CI_MERGE_REQUEST_IID ;
      else
        target_subdir=$CI_COMMIT_BRANCH ;
      fi
    - publish-pages $gnatcov_report_dir/html --target-subdir $target_subdir --expires 30

    # Compute coverage precentage
    - cobertura=$gnatcov_report_dir/cobertura/cobertura.xml
    - line_rate=$(cat $cobertura | grep -o 'line-rate="\([^"]\+\)"' | head -1 | grep -o '[0-9.]\+' || true )
    - line_perc=$(python -c "print($line_rate * 100)")
    - >
      echo "Line Coverage: $line_perc"

  coverage: '/^Line Coverage:\s+(\d+\.\d+)$/'
  artifacts:
    when: always #  Upload on errors too
    reports:
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage/cobertura/cobertura.xml
    paths:
      # Upload the entire reports/ directory as an artifact
      - reports/

# Target build.
pro:arm-elf:
  extends: .pro
  script:
    # Install the cross compiler
    - anod install gnat --qualifier=stable --target=arm-elf
    - eval $(anod printenv gnat --qualifier=stable --target=arm-elf)

    # Sanity check
    - arm-eabi-gnat --version

    # Remove the explicit dependency on `gnat_arm_elf` so we don't try to fetch
    # the community version.
    - alr -n -C traffic_light_qemu/ with --del gnat_arm_elf

    # Build
    - make build-target

community:x86_64-linux:
  stage: build
  extends:
     - .x86_64-linux-community
     - .default_rules
  script:
    # Setup
    - make setup-community

    # Build
    - make build-native

    # Test with coverage
    - make coverage-rts
    - make coverage-instrumentation
    - make coverage-build
    - make coverage-test-community
    - make coverage-report-cobertura
    - make coverage-report-text

  artifacts:
    when: always #  Upload on errors too
    paths:
      # Upload the entire reports/ directory as an artifact
      - reports/
