#!/usr/bin/env python3
"""Traceability check for the traffic-light-controller project.

Walks the requirements file and reports which FR/NFR IDs are referenced
in source code and tests via `-- @req <ID>[, <ID>...]` comments.

Exits 0 if all requirements are referenced in at least one of {code, tests},
1 otherwise. Use `--bootstrap` to warn instead of fail.

Also writes docs/requirements/traceability.md.

Usage:
    python3 tools/trace-check.py [--bootstrap]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRS = ROOT / "docs" / "requirements" / "srs.md"
TRACE_OUT = ROOT / "docs" / "requirements" / "traceability.md"
SRC = ROOT / "src"
TESTS = ROOT / "tests"

REQ_ID_RE = re.compile(r"\b(FR|NFR)-[A-Z]{2}-\d{2,}\b")
#  Ada-style `-- @req ...` for .ads/.adb/.gpr and `# @req ...` for .py.
ANNOTATION_RE = re.compile(r"(?:--|#)\s*@req\s+(.+)$")
OBSOLETE_RE = re.compile(r"~~((?:FR|NFR)-[A-Z]{2}-\d{2,})~~")


def collect_requirements(srs_path: Path) -> tuple[set[str], set[str]]:
    """Return (active_ids, obsolete_ids)."""
    text = srs_path.read_text(encoding="utf-8")
    obsolete = set(OBSOLETE_RE.findall(text))
    # Strip obsolete strikethroughs before scanning for active IDs.
    cleaned = OBSOLETE_RE.sub("", text)
    all_ids = set(m.group(0) for m in REQ_ID_RE.finditer(cleaned))
    active = all_ids - obsolete
    return active, obsolete


def collect_references(root: Path) -> dict[str, list[str]]:
    """Return {req_id: [file:line, ...]} from `-- @req` comments."""
    refs: dict[str, list[str]] = {}
    if not root.exists():
        return refs
    for path in root.rglob("*"):
        if path.is_dir() or path.suffix not in {
            ".ads", ".adb", ".gpr", ".md", ".py"
        }:
            continue
        try:
            for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
                m = ANNOTATION_RE.search(line)
                if not m:
                    continue
                ids = REQ_ID_RE.findall(m.group(1))
                # findall returns just the prefix groups; re-find full IDs:
                full_ids = REQ_ID_RE.findall(m.group(1))
                # Above duplicates; use a fresh scan for full match objects.
                for match in REQ_ID_RE.finditer(m.group(1)):
                    rid = match.group(0)
                    refs.setdefault(rid, []).append(
                        f"{path.relative_to(ROOT)}:{lineno}"
                    )
        except UnicodeDecodeError:
            continue
    return refs


def write_matrix(active: set[str], obsolete: set[str],
                 code_refs: dict[str, list[str]],
                 test_refs: dict[str, list[str]]) -> None:
    lines: list[str] = []
    lines.append("# Traceability Matrix\n")
    lines.append("> ⚠️ Auto-generated by `tools/trace-check.py`. Do not edit by hand.\n")
    lines.append("")
    lines.append("| Requirement | Code refs | Test refs | Status |")
    lines.append("|-------------|-----------|-----------|--------|")
    for rid in sorted(active):
        c = ", ".join(code_refs.get(rid, [])) or "—"
        t = ", ".join(test_refs.get(rid, [])) or "—"
        ok = "✅" if (code_refs.get(rid) or test_refs.get(rid)) else "❌"
        lines.append(f"| `{rid}` | {c} | {t} | {ok} |")
    if obsolete:
        lines.append("")
        lines.append("## Obsolete")
        lines.append("")
        for rid in sorted(obsolete):
            lines.append(f"- `{rid}`")
    TRACE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bootstrap", action="store_true",
                        help="Warn instead of failing on uncovered requirements.")
    args = parser.parse_args()

    if not SRS.exists():
        print(f"ERROR: {SRS} not found", file=sys.stderr)
        return 2

    active, obsolete = collect_requirements(SRS)
    code_refs = collect_references(SRC)
    test_refs = collect_references(TESTS)

    print(f"Active requirements: {len(active)}")
    print(f"Obsolete:            {len(obsolete)}")
    print(f"Code references:     {sum(len(v) for v in code_refs.values())}")
    print(f"Test references:     {sum(len(v) for v in test_refs.values())}")

    write_matrix(active, obsolete, code_refs, test_refs)
    print(f"Wrote {TRACE_OUT.relative_to(ROOT)}")

    uncovered = sorted(rid for rid in active
                       if not (code_refs.get(rid) or test_refs.get(rid)))
    if uncovered:
        print()
        print(f"Uncovered requirements ({len(uncovered)}):")
        for rid in uncovered:
            print(f"  {rid}")
        if args.bootstrap:
            print("Bootstrap mode: warning only.")
            return 0
        return 1

    print("All active requirements have at least one reference.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
