#!/usr/bin/env python3
"""Traceability check for the traffic-light-controller project.

Walks the requirements file and reports which FR/NFR IDs are referenced
in source code and tests via annotation comments:

  Coarse:       -- @req <ID>[, <ID>...]       (Ada)
                # @req <ID>[, <ID>...]        (Python)

  Fine-grained: -- @outcome (<name>) <ID>[, <ID>...]
                -- @pre (<name>) <ID>[, <ID>...]
                -- @type_contract (<name>) <ID>[, <ID>...]
                -- @rule_informal (<name>) <ID>[, <ID>...]

Also reads [verification-method] tags from srs.md and cross-checks that:
  [proof]   requirements have at least one code reference (fine-grained or coarse)
  [test]    requirements have at least one test reference
  [inspect] requirements get a warning (not failure) if missing code refs
  [hw-test] requirements get a warning (not failure) if missing refs

Exits 0 if all requirements are referenced in at least one of {code, tests},
1 otherwise. Use ``--bootstrap`` to warn instead of fail.

Also writes docs/requirements/traceability.md.

Usage:
    python3 tools/trace-check.py [--bootstrap]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRS = ROOT / "docs" / "requirements" / "srs.md"
TRACE_OUT = ROOT / "docs" / "requirements" / "traceability.md"
SRC = ROOT / "src"
TESTS = ROOT / "tests"

REQ_ID_RE = re.compile(r"\b(FR|NFR)-[A-Z]{2}-\d{2,}\b")
#  Ada-style `-- @req ...` for .ads/.adb/.gpr and `# @req ...` for .py.
ANNOTATION_RE = re.compile(r"(?:--|#)\s*@req\s+(.+)$")
OBSOLETE_RE = re.compile(r"~~((?:FR|NFR)-[A-Z]{2}-\d{2,})~~")

#  Fine-grained SPARK Process tags (Ada only).
SPARK_TAG_RE = re.compile(
    r"--\s*@(outcome|pre|type_contract|rule_informal)"
    r"\s+\([^)]+\)\s+(.+)$"
)

#  Verification-method tag in srs.md: e.g. **FR-PH-01** `[test]`
VMETHOD_RE = re.compile(
    r"\*\*((?:FR|NFR)-[A-Z]{2}-\d{2,})\*\*\s+`\[(proof|test|inspect|hw-test)\]`"
)


def collect_requirements(srs_path: Path) -> tuple[set[str], set[str], dict[str, str]]:
    """Return (active_ids, obsolete_ids, {id: verification_method})."""
    text = srs_path.read_text(encoding="utf-8")
    obsolete = set(OBSOLETE_RE.findall(text))
    # Strip obsolete strikethroughs before scanning for active IDs.
    cleaned = OBSOLETE_RE.sub("", text)
    all_ids = set(m.group(0) for m in REQ_ID_RE.finditer(cleaned))
    active = all_ids - obsolete

    # Parse verification-method tags.
    vmethods: dict[str, str] = {}
    for m in VMETHOD_RE.finditer(text):
        vmethods[m.group(1)] = m.group(2)

    return active, obsolete, vmethods


def collect_references(root: Path) -> dict[str, list[str]]:
    """Return {req_id: [file:line, ...]} from `-- @req` and fine-grained tags."""
    refs: dict[str, list[str]] = {}
    if not root.exists():
        return refs
    for path in root.rglob("*"):
        if path.is_dir() or path.suffix not in {
            ".ads", ".adb", ".gpr", ".md", ".py"
        }:
            continue
        try:
            for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
                loc = f"{path.relative_to(ROOT)}:{lineno}"

                # Coarse @req annotation.
                m = ANNOTATION_RE.search(line)
                if m:
                    for match in REQ_ID_RE.finditer(m.group(1)):
                        rid = match.group(0)
                        refs.setdefault(rid, []).append(loc)
                    continue

                # Fine-grained SPARK tags.
                m = SPARK_TAG_RE.search(line)
                if m:
                    for match in REQ_ID_RE.finditer(m.group(2)):
                        rid = match.group(0)
                        refs.setdefault(rid, []).append(
                            f"{loc} @{m.group(1)}"
                        )
        except UnicodeDecodeError:
            continue
    return refs


def write_matrix(active: set[str], obsolete: set[str],
                 vmethods: dict[str, str],
                 code_refs: dict[str, list[str]],
                 test_refs: dict[str, list[str]]) -> None:
    lines: list[str] = []
    lines.append("# Traceability Matrix\n")
    lines.append("> Auto-generated by `tools/trace-check.py`. Do not edit by hand.\n")
    lines.append("")
    lines.append("| Requirement | Method | Code refs | Test refs | Status |")
    lines.append("|-------------|--------|-----------|-----------|--------|")
    for rid in sorted(active):
        vm = vmethods.get(rid, "?")
        c = ", ".join(code_refs.get(rid, [])) or "—"
        t = ", ".join(test_refs.get(rid, [])) or "—"
        ok = "✅" if (code_refs.get(rid) or test_refs.get(rid)) else "❌"
        lines.append(f"| `{rid}` | `[{vm}]` | {c} | {t} | {ok} |")
    if obsolete:
        lines.append("")
        lines.append("## Obsolete")
        lines.append("")
        for rid in sorted(obsolete):
            lines.append(f"- `{rid}`")
    TRACE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def check_vmethods(active: set[str], vmethods: dict[str, str],
                   code_refs: dict[str, list[str]],
                   test_refs: dict[str, list[str]]) -> tuple[list[str], list[str]]:
    """Cross-check verification methods. Returns (errors, warnings)."""
    errors: list[str] = []
    warnings: list[str] = []

    unclassified = sorted(rid for rid in active if rid not in vmethods)
    if unclassified:
        errors.append(
            f"MR-07: {len(unclassified)} requirement(s) missing "
            f"[verification-method] tag: {', '.join(unclassified)}"
        )

    for rid in sorted(active):
        vm = vmethods.get(rid)
        has_code = bool(code_refs.get(rid))
        has_test = bool(test_refs.get(rid))

        if vm == "proof":
            if not has_code:
                errors.append(
                    f"{rid} [{vm}]: no code reference (needs @outcome/@pre/"
                    f"@type_contract or @req in SPARK source)"
                )
        elif vm == "test":
            if not has_test:
                errors.append(
                    f"{rid} [{vm}]: no test reference"
                )
        elif vm == "inspect":
            if not has_code:
                warnings.append(
                    f"{rid} [{vm}]: no code reference (recommended but not required)"
                )
        elif vm == "hw-test":
            if not has_code and not has_test:
                warnings.append(
                    f"{rid} [{vm}]: no code or test reference "
                    f"(hardware-only, warning only)"
                )

    return errors, warnings


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bootstrap", action="store_true",
                        help="Warn instead of failing on uncovered requirements.")
    args = parser.parse_args()

    if not SRS.exists():
        print(f"ERROR: {SRS} not found", file=sys.stderr)
        return 2

    active, obsolete, vmethods = collect_requirements(SRS)
    code_refs = collect_references(SRC)
    test_refs = collect_references(TESTS)

    print(f"Active requirements: {len(active)}")
    print(f"Obsolete:            {len(obsolete)}")
    print(f"Classified:          {len(vmethods)}/{len(active)}")
    print(f"Code references:     {sum(len(v) for v in code_refs.values())}")
    print(f"Test references:     {sum(len(v) for v in test_refs.values())}")

    write_matrix(active, obsolete, vmethods, code_refs, test_refs)
    print(f"Wrote {TRACE_OUT.relative_to(ROOT)}")

    uncovered = sorted(rid for rid in active
                       if not (code_refs.get(rid) or test_refs.get(rid)))

    vmethod_errors, vmethod_warnings = check_vmethods(
        active, vmethods, code_refs, test_refs
    )

    rc = 0

    if uncovered:
        print()
        print(f"Uncovered requirements ({len(uncovered)}):")
        for rid in uncovered:
            print(f"  {rid}")
        if not args.bootstrap:
            rc = 1

    if vmethod_warnings:
        print()
        print(f"Verification-method warnings ({len(vmethod_warnings)}):")
        for w in vmethod_warnings:
            print(f"  {w}")

    if vmethod_errors:
        print()
        print(f"Verification-method errors ({len(vmethod_errors)}):")
        for e in vmethod_errors:
            print(f"  {e}")
        if not args.bootstrap:
            rc = 1

    if rc == 0:
        if uncovered and args.bootstrap:
            print("\nBootstrap mode: warnings only.")
        elif not uncovered and not vmethod_errors:
            print("\nAll active requirements have at least one reference.")
            if vmethods and len(vmethods) == len(active):
                print("All requirements are classified per MR-07.")

    return rc


if __name__ == "__main__":
    sys.exit(main())
